### ISSUE TITLE
Excel转html时，如何添加<title>?

### ISSUE THREAD

**Issue by ZCHWorld** [aspose-cells/Aspose.Cells-for-Java#42]
把Excel转html后，我会把该静态页面直接浏览器打开，但没有title，如何在转换时添加<title>fileName</title>？

**Comment by ZCHWorld** [comment]
我自己找到了：
String title = "excel name";
String sourcePath = "d:\test.xlsx",savePath = "d:\test.html";
Workbook workbook = new Workbook(sourcePath);
HtmlSaveOptions options = new HtmlSaveOptions();
options.setPageTitle(title);
workbook.save(savePath, options)

**Comment by amjad-sahi** [comment]
Aspose.Cells follows MS Excel standards and specifications when parsing or rendering HTMLs. Did you verify if MS Excel gives different results than what Aspose.Cells gives for exporting HTML when saving as as "Web Page" in MS Excel manually. If you think MS Excel works other way and can render as per your desired results using specific options, please provide your sample files (input and output) and some screenshots to highlight it, we will check it on how to do it via Aspose.Cells APIs.

PS. you may upload the files to some file sharing service (e.g Dropbox, Google drive, etc.) and share the Download link.

**Comment by amjad-sahi** [comment]
I guess your issue is sorted out now by using your code segment. Feel free to contact us any time if you need further help or have some other issue queries, we will be happy to assist you soon.
