### ISSUE TITLE
Worksheet.autoFitColumns produces ugly result

### ISSUE THREAD

**Issue by j75** [aspose-cells/Aspose.Cells-for-Java#51]
I am converting an XLSX to PDF, essentially using the same code as in issue #48.

Using `Worksheet#autoFitColumns()` when converting the following file
[example.xlsx](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/5416801/example.xlsx)
produces an ugly result :
[example-w_autoFit.pdf](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/5416814/example-w_autoFit.pdf)
(just look at the width of the columns Cecilia, Patty, Robert and Frank).

Without `autoFitColumns` the result is OK :
[example-normal.pdf](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/5416821/example-normal.pdf)

The code is essentially the same as in the #48 issue (https://github.com/aspose-cells/Aspose.Cells-for-Java/issues/48).
I have used Aspose library 20.10 on an Ubuntu 18.04 system.

What can I do to improve the result when using `autoFitColumns` ?

**Comment by amjad-sahi** [comment]
@j75,

Why do you apply auto-fit columns operation upon your data in the worksheet of this file? I am afraid, you should not apply auto-fit operation for specific worksheets/files where necessary, the operation is not supposed to implement in each sheet. Aspose.Cells works the same way as MS Excel does regarding auto-fit rows/cols function. For confirmation, please open the file into MS Excel manually and apply auto-fit column operation upon certain columns (e.g. select column by clicking on the header,  "E" and then double-click the handle (joining line b/w E and F ), you will see the similar results. In short, this is not an issue with Aspose.Cells APIs.

**Comment by j75** [comment]
> Why do you apply auto-fit columns operation upon your data in the worksheet of this file?

This is what I did to overcome the issue #48 ; if I understand correctly, the recommended way would have been to auto-fit only cells that contain data type values (this was the problem of the afore-mentioned issue).

**Comment by amjad-sahi** [comment]
@j75,

Yes, you do not need to apply auto-fit operation upon the column in this file.
