### ISSUE TITLE
Aspose.cells.gridweb-java Chinese garbled

### ISSUE THREAD

**Issue by huosenyuan** [aspose-cells/Aspose.Cells-for-Java#58]
![image](https://user-images.githubusercontent.com/30994824/113844250-dce13e80-97c6-11eb-8ea3-63a58ee516f9.png)

**Comment by amjad-sahi** [comment]
@huosenyuan,

Please zip and post your Excel file, we will check it soon. Also, you may post your issue with sample file (zipped archive) in the Aspose.Cells [forum](https://forum.aspose.com/c/cells/9).

**Comment by huosenyuan** [comment]
[data.zip](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/6271757/data.zip)
this is excel file

**Comment by huosenyuan** [comment]
I use it Examples.GridWeb , access the EXCEL form of Chinese content, and display garbled code in the browser.

**Comment by amjad-sahi** [comment]
I opened your file into MS Excel 2016 and found this display as in the [screenshot](https://i.imgur.com/urSmKJZ.png). So, I found no Chinese chars shown in the cells.

**Comment by huosenyuan** [comment]
![image](https://user-images.githubusercontent.com/30994824/113895912-05376000-97fc-11eb-971a-e16744cb4c9b.png)

**Comment by huosenyuan** [comment]
[data.xls](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/6272887/data.xls)

**Comment by huosenyuan** [comment]
[Uploading Examples.GridWeb.zip…]()
![image](https://user-images.githubusercontent.com/30994824/113955213-e2359c00-984d-11eb-96a0-a7f7598540d8.png)

**Comment by huosenyuan** [comment]
[Examples.GridWeb.zip](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/6275419/Examples.GridWeb.zip)
![image](https://user-images.githubusercontent.com/30994824/113955392-36d91700-984e-11eb-97a4-a4b5dd5460bf.png)

**Comment by amjad-sahi** [comment]
@huosenyuan,

@huosenyuan,

I did test your scenario/case in a separate web project using latest Aspose.Cells.GridWeb for Java v21.3 with its latest resource files (please use latest files in acw_client folder of Aspose.Cells.GridWeb for Java v21.3) in eclipse. I used a simple .jsp page having following source code. It simply imports the “chineseData.xls” file into GridWeb and it works fine.
e.g.
**Sample code:**

```
%@ page language="java" contentType="text/html; charset=UTF-8"
 import="com.aspose.gridweb.*,java.io.*" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>

<%
ExtPage BeanManager=ExtPage.getInstance();
BeanManager.setServlet(request, response);
BeanManager.setPageaction( request.getContextPath()+"/GridWebServlet"); 
BeanManager.setPageajaxcallpath(request.getContextPath()+"/GridWebServlet?acw_ajax_call=true"); 
GridWebBean gridweb=BeanManager.getBean();
gridweb.setACWClientPath("../grid/acw_client/");
%>
<%@include file="/head.jsp" %>
</head>
<BODY>
<%
gridweb.setEnableAsync(true);
gridweb.setRenderHiddenRow(true);
gridweb.setWidth(Unit.Pixel(1200));
gridweb.setHeight(Unit.Pixel(600));
 String file="f:\\Files\\online excel viewer\\WebContent\\file\\chineseData.xls";

gridweb.importExcelFile(file);
 gridweb.prepareRender();
out.println(gridweb.getHTMLBody());
  %>
  <br>
 
</BODY>
</html>
```
I am using Tomcat v7.0 server with JDK1.7 and Google chrome browser type. See the screenshot attached that shows Chinese chars are displayed fine.
https://i.imgur.com/G9udg5x.png

Which browser type you are using? Please note, it does not look good in eclipse IDE editor.
