### ISSUE TITLE
转pdf时如何设置缩放参数

### ISSUE THREAD

**Issue by biaoy76** [aspose-cells/Aspose.Cells-for-Java#70]
如标题，Microsoft Excel在打印预览时，有缩放参数【无缩放】、【将工作表调整为一页】、【将所有列调整为一页】、【将所有行调整为一页】，那使用Aspose.Cell时，如何设置这些参数

**Comment by amjad-sahi** [comment]
@biaoy76,

您可以尝试使用 [setOnePagePerSheet](https://reference.aspose.com/cells/java/com.aspose.cells/pdfsaveoptions/#setOnePagePerSheet-boolean-) 为每个工作表呈现一页和 [setAllColumnsInOnePagePerSheet](https:/ /reference.aspose.com/cells/java/com.aspose.cells/pdfsaveoptions/#setAllColumnsInOnePagePerSheet-boolean-) 根据您的需要在单个 PDF 页面上呈现所有列。

请参阅包含示例代码的文档以供您完整参考。
https://docs.aspose.com/cells/java/render-one-pdf-page-per-excel-worksheet-excel-to-pdf-conversion/
https://docs.aspose.com/cells/java/fit-all-worksheet-columns-on-single-pdf-page/

希望这个对你有帮助。

如果您有进一步的疑问或问题，请在专门的 [[论坛](https://forum.aspose.com/)] 中发帖。
