### ISSUE TITLE
特定的xls 文件 转换 json 报错  com.aspose.cells.CellsException: Corrupted file

### ISSUE THREAD

**Issue by jieLi086** [aspose-cells/Aspose.Cells-for-Java#71]
xls  to json 显示如下报错
![企业微信截图_16920869188456](https://github.com/aspose-cells/Aspose.Cells-for-Java/assets/72288353/69ddba85-38a4-4831-935b-4c6a5011a02b)

源文件
[bugFile.xls](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/12356696/bugFile.xls)

**Comment by amjad-sahi** [comment]
@jieLi086,

我检查了您的 Excel 模板文件，发现它已损坏。 当我在 MS Excel (2019) 中手动打开您的文件时，MS Excel 给出错误（请参阅随附的屏幕截图）。 简而言之，如果文件损坏，Aspose.Cells 将抛出损坏的文件异常。 请使用有效的Excel文件（可以正常打开，没有任何异常）并根据您的场景/案例进行尝试，它会正常工作。
![sc_shot1](https://github.com/aspose-cells/Aspose.Cells-for-Java/assets/17720471/d4b49acc-fcc6-4b6e-92cc-54658861e797)

如果您仍有任何困惑或疑问，请告诉我们。

**Comment by jieLi086** [comment]
好的 谢谢
