### ISSUE TITLE
特定xls格式文件转成xlsx格式时，部分shape丢失

### ISSUE THREAD

**Issue by liyan1044120608** [aspose-cells/Aspose.Cells-for-Java#72]
![image](https://github.com/aspose-cells/Aspose.Cells-for-Java/assets/52479191/326f06a5-297f-4681-aab4-b7905c5fd82a)

[源文件.xls](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/14427726/default.xls)

[使用aspose转的.xlsx](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/14427731/aspose.xlsx)

[使用Excel另存为的.xlsx](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/14427732/Excel.xlsx)

**Comment by amjad-sahi** [comment]
@liyan1044120608,

 感谢您提供示例文件。

您正在使用哪个版本的 Aspose.Cells for Java API？ 我使用以下示例代码使用最新版本/修复程序（Aspose.Cells for Java v24.2）测试了您的场景/案例，它工作正常且符合预期。 输出 XLSX（附件）文件中的形状不会丢失。
```java
Workbook wb = new Workbook("f:\\files\\default.xls");
wb.save("f:\\files\\out1.xlsx");
````
[out1.xlsx](https://github.com/aspose-cells/Aspose.Cells-for-Java/files/14432200/out1.xlsx)

请尝试使用我们的最新版本（Aspose.Cells for Java v24.2）：
[Releases](https://releases.aspose.com/cells/java/) | [Maven](https://releases.aspose.com/java/repo/com/aspose/aspose-cells/)

如果您仍然发现任何问题，请告诉我们详细信息和示例代码？
